# -*- coding: utf-8 -*-
"""
gemini_client/unofficial_live/official_adapter.py
===================================================
Official Gemini Live API Message Adapter.

Constructs and parses JSON payloads matching the official Google Gemini Live
WebSocket protocol (v1beta GenerativeService.BidiGenerateContent):
  - SetupComplete: {"setupComplete": {}}
  - ServerContent: {"serverContent": {"modelTurn": {"parts": [...]}, "turnComplete": bool, "interrupted": bool}}
  - RealtimeInput: {"realtimeInput": {"mediaChunks": [...]}}
  - ClientContent: {"clientContent": {"turns": [...], "turnComplete": bool}}
"""
from __future__ import annotations

import base64
import json
from typing import Any, Dict, List, Optional, Union


def build_setup_complete() -> Dict[str, Any]:
    """Construct official BidiGenerateContentSetupComplete payload."""
    return {"setupComplete": {}}


def build_server_content(
    text: Optional[str] = None,
    pcm_bytes: Optional[bytes] = None,
    mime_type: str = "audio/pcm;rate=24000",
    turn_complete: bool = False,
    interrupted: bool = False,
) -> Dict[str, Any]:
    """
    Construct official BidiGenerateContentServerContent payload.

    Parameters
    ----------
    text : str, optional
        Text chunk generated by the model.
    pcm_bytes : bytes, optional
        PCM audio bytes generated by the model.
    mime_type : str
        Audio mime type string. Default "audio/pcm;rate=24000".
    turn_complete : bool
        True if this is the final message of the turn.
    interrupted : bool
        True if the generation was interrupted by user barge-in.

    Returns
    -------
    dict
        Official Gemini Live WebSocket payload.
    """
    parts: List[Dict[str, Any]] = []

    if text:
        parts.append({"text": text})

    if pcm_bytes:
        encoded_audio = base64.b64encode(pcm_bytes).decode("ascii")
        parts.append({
            "inlineData": {
                "mimeType": mime_type,
                "data": encoded_audio,
            }
        })

    model_turn: Dict[str, Any] = {"parts": parts} if parts else {}

    server_content: Dict[str, Any] = {
        "turnComplete": turn_complete,
        "interrupted": interrupted,
    }

    if model_turn:
        server_content["modelTurn"] = model_turn

    return {"serverContent": server_content}


def parse_client_message(raw_msg: Union[str, bytes]) -> Dict[str, Any]:
    """
    Parse an incoming client WebSocket JSON payload.

    Extracts:
      - action: 'setup', 'client_content', 'realtime_input', or 'unknown'
      - text: str if text was sent
      - media: bytes if audio/image media chunk was sent
      - mime_type: str
    """
    try:
        if isinstance(raw_msg, bytes):
            raw_msg = raw_msg.decode("utf-8")
        data = json.loads(raw_msg)
    except Exception:
        return {"action": "unknown", "raw": raw_msg}

    # 1. Setup message
    if "setup" in data:
        return {
            "action": "setup",
            "model": data["setup"].get("model", "models/gemini-2.0-flash-live-001"),
            "system_instruction": data["setup"].get("systemInstruction"),
        }

    # 2. Client Content (Text prompt)
    if "clientContent" in data:
        cc = data["clientContent"]
        turns = cc.get("turns", [])
        extracted_text = ""
        for turn in turns:
            parts = turn.get("parts", [])
            for p in parts:
                if "text" in p:
                    extracted_text += p["text"]
        return {
            "action": "client_content",
            "text": extracted_text,
            "turn_complete": cc.get("turnComplete", True),
        }

    # 3. Realtime Input (Media Chunk)
    if "realtimeInput" in data:
        ri = data["realtimeInput"]
        chunks = ri.get("mediaChunks", [])
        media_bytes = b""
        mime_type = "audio/pcm;rate=16000"
        for chunk in chunks:
            mime_type = chunk.get("mimeType", mime_type)
            b64_data = chunk.get("data", "")
            if b64_data:
                try:
                    media_bytes += base64.b64decode(b64_data)
                except Exception:
                    pass
        return {
            "action": "realtime_input",
            "media": media_bytes,
            "mime_type": mime_type,
        }

    return {"action": "unknown", "data": data}
